package com.dcen.wallet.dellet.core.bip44.constant

/**
 * Created by「 The Khaeng 」on 06 Jul 2018 :)
 */
object BIP44CoinType {

    // TODO: contribute coin type
    const val NO_CRYPTO = -1
    const val BTC = 0
    const val BTC_TEST_NET = 1
    const val LTC = 2       //Litecoin
    const val DOGE = 3      //Dogecoin
    const val RDD = 4       //Reddcoin
    const val DSH = 5       //Dash
    const val NMC = 6       //Namecoin
    const val PPC = 7       //Peercoin
    const val FTC = 8       //Feathecoin
    const val XCP = 9       //Counterparty
    const val BLK = 10      //Blackcoin
    const val NSR = 11      //NuShares
    const val NBT = 12      //NuBits
    const val MZC = 13      //Mazacoin
    const val VIA = 14      //Viacoin
    const val XCH = 15      //ClearingHouse
    const val RBY = 16      //Rubycoin
    const val GRS = 17      //Groestlcoin
    const val DGC = 18      //Digitalcoin
    const val CCN = 19      //Cannacoin
    const val DGB = 20      //DigiByte
    const val MONA = 22     //Monacoin
    const val CLAM = 23     //Clams
    const val XPM = 24      //Primecoin
    const val NEOS = 25     //Neoscoin
    const val JBS = 26      //Jumbucks
    const val ZRC = 27      //ziftrCOIN
    const val VTC = 28      //Vertcoin
    const val NXT = 29      //NXT
    const val BURST = 30    //Burst
    const val MUE = 31      //MonetaryUnit
    const val ZOOM = 32     //Zoom
    const val VPN = 33      //Vpncoin
    const val CDN = 34      //Canada eCoin
    const val SDC = 35      //ShadowCash
    const val PKB = 36      //ParkByte
    const val PND = 37      //Pandacoin
    const val START = 38    //StartCOIN
    const val MOIN = 39     //MOIN
    const val EXP = 40      //Expanse
    const val EMC2 = 41     //Einsteinium
    const val DCR = 42      //Decred
    const val XEM = 43      //NEM
    const val PART = 44     //Particl
    const val ARG = 45      //Argentum
    const val SHR = 48      //Shreeji
    const val GCR = 49      //Global Currency Reserve (GCRcoin)
    const val NVC = 50      //Novacoin
    const val AC = 51       //Asiacoin
    const val BTCD = 52     //Bitcoindark
    const val DOPE = 53     //Dopecoin
    const val TPC = 54      //Templecoin
    const val AIB = 55      //AIB
    const val EDRC = 56     //EDRCoin
    const val SYS = 57      //Syscoin
    const val SLR = 58      //Solarcoin
    const val SMLY = 59     //Smileycoin
    const val ETH = 60      //Etheruem
    const val CMP = 71      //Compcoin
    const val CRW = 72      //Crown
    const val BELA = 73     //BelaCoin
    const val VASH = 74     //Virtual Cash the new version of Vpncoin
    const val FJC = 75      //FujiCoin
    const val MIX = 76      //MIX
    const val XVG = 77      //Verge
    const val EFL = 78      //Electronic Gulden
    const val CLUB = 79     //ClubCoin
    const val RICHX = 80    //RichCoin
    const val POT = 81      //Potcoin
    const val QRK = 82      //Quarkcoin
    const val TRC = 83      //Terracoin
    const val GRC = 84      //Gridcoin
    const val AUR = 85      //Auroracoin
    const val IXC = 86      //IXCoin
    const val NLG = 87      //Gulden
    const val BITB = 88     //BitBean
    const val BTA = 89      //Bata
    const val XMY = 90      //Myriadcoin
    const val BSD = 91      //BitSend
    const val UNO = 92      //Unobtanium
    const val MTR = 93      //MasterTrader
    const val GB = 94       //GoldBlocks
    const val SHM = 95      //Saham
    const val CRX = 96      //Chronos
    const val BIQ = 97      //Ubiquoin
    const val EVO = 98      //Evotion
    const val STO = 99      //SaveTheOcean
    const val BIGUP = 100   //BigUp
    const val GAME = 101    //GameCredits
    const val DLC = 102     //Dollarcoins
    const val ZYD = 103     //Zayedcoin
    const val DBIC = 104    //Dubaicoin
    const val STRAT = 105   //Stratis
    const val SH = 106      //Shilling
    const val MARS = 107    //MarsCoin
    const val UBQ = 108     //Ubiq
    const val PTC = 109     //Pesetacoin
    const val NRO = 110     //Neurocoin
    const val ARK = 111     //ARK
    const val USC = 112     //UltimateSecureCashMain
    const val THC = 113     //Hempcoin
    const val LINX = 114    //Linx
    const val ECN = 115     //Ecoin
    const val DNR = 116     //Chronos
    const val PINK = 117    //Pinkcoin
    const val PIGGY = 118   //PiggyCoin
    const val PIVX = 119    //Pivx
    const val FLASH = 120   //Flashcoin
    const val ZEN = 121     //Zencash
    const val PUT = 122     //Putincoin
    const val ZNY = 123     //BitZeny
    const val UNIFY = 124   //Unify
    const val XST = 125     //StealthCoin
    const val BRK = 126     //Breakout Coin
    const val VC = 127      //Vcash
    const val XMR = 128     //Monero
    const val VOX = 129     //Voxels
    const val NAV = 130     //NavCoin
    const val FCT = 131     //Factom Factoids
    const val EC = 132      //Factom Entry Credits
    const val ZEC = 133     //Zcash
    const val LSK = 134     //Lisk
    const val STEEM = 135   //Steem
    const val XZC = 136     //ZCoin
    const val RSK = 137     //RSK
    const val RPT = 139     //RealPointCoin
    const val LBC = 140     //LBRY Credits
    const val KMD = 141     //Komodo
    const val BSQ = 142     //bisq Token
    const val RIC = 143     //Riecoin
    const val XRP = 144     //Ripple
    const val BCH = 145     //Bitcoin Cash
    const val NEBL = 146    //Neblio
    const val ZCL = 147     //ZClassic
    const val XLM = 148     //Stellar Lumens
    const val NLC2 = 149    //NoLimitCoin2
    const val WHL = 150     //WhaleCoin
    const val ERC = 151     //EuropeCoin
    const val DMD = 152     //Diamond
    const val BTM = 153     //Bytom
    const val BIO = 154     //Biocoin
    const val XWC = 155     //Whitecoin
    const val BTG = 156     //Bitcoin Gold
    const val BTC2X = 157   //Bitcoin 2x
    const val SSN = 158     //SuperSkynet
    const val TOA = 159     //TOACoin
    const val BTX = 160     //Bitcore
    const val ACC = 161     //Adcoin
    const val ELLA = 163    //Ellaism
    const val PIRL = 164    //Pirl
    const val XRB = 165     //RaiBlocks
    const val VIVO = 166    //Vivo
    const val FRST = 167    //Firstcoin
    const val HNC = 168     //Helleniccoin
    const val BUZZ = 169    //BUZZ
    const val MBRS = 170    //Ember
    const val HSR = 171     //Hcash
    const val HTML = 172    //HTMLCOIN
    const val ODN = 173     //Obsidian
    const val ONX = 174     //OnixCoin
    const val RVN = 175     //Ravencoin
    const val GBX = 176     //GoByte
    const val BTCZ = 177    //BitcoinZ
    const val POA = 178     //Poa
    const val NYC = 179     //NewYorkCoin
    const val MXT = 180     //MarteXcoin
    const val WC = 181      //Wincoin
    const val MNX = 182     //Minexcoin
    const val BTCP = 183    //Bitcoin Private
    const val MUSIC = 184   //Musicoin
    const val BCA = 185     //Bitcoin Atom
    const val CRAVE = 186   //Crave
    const val STAK = 187    //STRAKS
    const val WBTC = 188    //World Bitcoin
    const val LCH = 189     //LiteCash
    const val EXCL = 190    //ExclusiveCoin
    const val LCC = 192     //LitecoinCash
    const val XFE = 193     //Feirm
    const val EOS = 194     //EOS
    const val TRX = 195     //Tron
    const val KOBO = 196    //Kobocoin
    const val HUSH = 197    //HUSH
    const val BANANO = 198  //Bananos
    const val ETF = 199     //ETF
    const val OMNI = 200    //Omni
    const val BIFI = 201    //BitcoinFile
    const val UFO = 202     //Uniform Fiscal Object
    const val CNMC = 203    //Cryptonodes
    const val NRG = 204     //Energi
    const val RIN = 205     //Ringo
    const val ATP = 206     //PlatON
    const val EVT = 207     //everiToken
    const val ATN = 208     //ATN
    const val BIS = 209     //Bismuth
    const val NEET = 210    //NEETCOIN
    const val BOPO = 211    //BopoChain
    const val BOXY = 215    //BoxyCoin
    const val FLO = 216     //Flo
    const val BITG = 222    //Bitcoin Green
    const val ASK = 223     //AskCoin
    const val SMART = 224   //Smartcash
    const val XUEZ = 225    //XUEZ
    const val VAR = 233     //Varda
    const val NIM = 242     //Nimiq
    const val UC = 247      //Ulord
    const val NANO = 256    //Bitcoin Nano
    const val ZEST = 259    //Zest
    const val ONE = 271     //ONE
    const val SBC = 299     //SBC
    const val GNX = 300     //Genaro Network
    const val ARA = 312     //Aura
    const val RAP = 321     //Rapture
    const val BLOCK = 328   //Blocknet
    const val MEM = 333     //MemCoin
    const val AION = 425    //Aion
    const val PHR = 444     //Phore
    const val KOTO = 510    //Koto
    const val XRD = 512     //Radiant
    const val YAP = 528     //Yapstone
    const val BCS = 555     //Bitcoin Smart
    const val EAST = 625    //Eastcoin
    const val ACT = 666     //Achain
    const val SSC = 668     //SelfSell
    const val BTW = 777     //Bitcoin World
    const val BEET = 800    //Beetle Coin
    const val QVT = 808     //Qvolta
    const val VET = 818     //VeChain Token
    const val CLO = 820     //Callisto
    const val ADF = 886     //AD Token
    const val NEO = 888     //NEO
    const val XSEL = 890    //Seln
    const val LBTC = 998    //Lightning Bitcoin
    const val BCD = 999     //Bitcoin Diamond
    const val BTN = 1000    //Bitcoin New
    const val ONT = 1024    //Ontology
    const val BBC = 1111    //Big Bitcoin
    const val CMT = 1122    //CyberMiles Token
    const val ETSC = 1128   //Ethereum Social
    const val CDY = 1145    //Bitcoin Candy
    const val DFC = 1337    //Defcoin
    const val HYC = 1397    //Hycon
    const val BCX = 1688    //BitcoinX
    const val XTZ = 1729    //Tezos
    const val ADA = 1815    //Cardano
    const val TES = 1856    //Teslacoin
    const val CLC = 1901    //Classica
    const val VIPS = 1919   //VIPSTARCOIN
    const val XMX = 1977    //Xuma
    const val EGEM = 1987   //EtherGem
    const val HODL = 1989   //HOdlcoin
    const val POLIS = 1997  //Polis
    const val EOSC = 2018   //EOSClassic
    const val QTUM = 2301   //QTUM
    const val ETP = 2302    //Metaverse
    const val DEO = 3552    //Destocoin
    const val NAS = 2718    //Nebulas
    const val ROI = 3377    //ROIcoin
    const val IOTA = 4218   //IOTA
    const val AXE = 4242    //Axe
    const val FIC = 5248    //FIC
    const val GO = 6060     //GoChain GO
    const val BPA = 6666    //Bitcoin Pizza
    const val SAFE = 6688   //SAFE
    const val ROGER = 6969  //TheHolyrogerCoin
    const val BTV = 7777    //Bitvote
    const val BTQ = 8339    //BitcoinQuark
    const val SBTC = 8888   //Super Bitcoin
    const val BTP = 8999    //Bitcoin Pay
    const val BTF = 9888    //Bitcoin Faith
    const val GOD = 9999    //Bitcoin God
    const val PWR = 22504   //PWRcoin
    const val ESN = 31102   //EtherSocial Network
    const val BTCS = 33878     //Bitcoin Stake
    const val WICC = 99999     //Waykichain
    const val LAX = 1712144    //LAPO
    const val BCO = 5249353    //BitcoinOre
    const val WAN = 5718350    //Wanchain
    const val WAVES = 5741564  //Waves
    const val kUSD = 91927009  //kUSD
}
